# Temporary config file,
# To be merged when the rest of the framework is implemented
# Currently read from generated.py
obstacles:
    - type: "shelf"
      position:
        x: -1.25
        y: -1
        z: 0
      rotation:
        r: 90
        p: 0
        y: 0
      params:
        rows: 5
        cols: 5
        element_size: .5
        shelf_depth: .5
        wall_thickness: .01
    - type: "shelf"
      position:
        x: -1.25
        y: 1.5
        z: 0
      rotation:
        r: 90
        p: 0
        y: 0
      scale: 1
      params:
        rows: 5
        cols: 5
        element_size: .5
        shelf_depth: .5
        wall_thickness: .01
        move:
          - position:
              x: -2.5
              y: 0.5
              z: 1.4
          - position:
              x: 2.5
              y: 0.5
              z: 1.4
    - type: "human"
      position:
        x: 5
        y: 5
        z: 0
      rotation:
        r: 0
        p: 0
        y: 0
      scale: 1
      params:
        move:
          - position:
              x: -2.5
              y: 0.5
              z: 1.4
          - position:
              x: 2.5
              y: 0.5
              z: 1.4
    # - type: "human"
    #   position:
    #     x: -5
    #     y: -5
    #     z: 0
    #   rotation:
    #     r: 0
    #     p: 0
    #     y: 0
    #   scale: 2
