# config that builds the env as Yifan had it
run:
  load_model: False  
  model_path: ""  
  train:
    num_envs : 32
    timesteps: 5000000 
    save_freq : 50000
    save_folder: "./models/weights"  
    save_name: "PPO_tableworld_two"
    recurrent: False
    ppo_steps: 256  
    batch_size: 2048
    gamma: 0.99321012399
    tensorboard_folder: "./models/tensorboard_logs"
    custom_policy:
      use: "CustomFeaturesExtractor"
      args:
        features_dim: 69
      activation_function: "ReLU"  
      layers:
        - value_function:
          - 64
          - 32
        - policy_function:
          - 128
          - 64
          - 32
          - 16   
      lstm:
        lstm_hidden_size: 512
        n_lstm_layers: 2
        shared_lstm: False
        enable_critic_lstm: True

  eval:
    max_episodes: -1  
    logging: 1
    display_delay: 0.00416666666 

env:
  max_steps_per_episode: 1024  
  use_physics_sim: True  # strictly speaking the original code had this at False
  physics_steps_per_env_step: 1
  sim_step: 0.00416666666  
  stat_buffer_size: 25  
  normalize_observations: False
  normalize_rewards: False
  robots:
    - type: "UR5_P2P" 
      config:
        name: "ur5_1"
        base_position: [0, 0, 1.1]
        base_orientation: [0, 0, 0]
        resting_angles: [90, 90, 90, 90, 0, 0]
        control_mode: 2
        xyz_delta: 0.005
        rpy_delta: 0.005
      sensors:
        - type: "ObstacleCenterRadius"
          config:
            name: "ocr"
            max_obstacles: 100
      goal:
        type: "JointsCollision"
        config:
          add_to_logging: True
          continue_after_success: True
          reward_success: 50
          reward_collision: -10
          reward_distance_mult: -0.001
          dist_threshold_start: 3
          dist_threshold_end : 0.1
          dist_threshold_increment_start: 0.01
          dist_threshold_increment_end: 0.001
          dist_threshold_overwrite: "None"

  world:
    type: "Table"
    config:
      workspace_boundaries: [-1.5, 1.5, -1.2, 1.2, 1.1, 2]
      num_static_obstacles: 5
      num_moving_obstacles: 5
      box_measurements: [0.025, 0.075, 0.025, 0.075, 0.00075, 0.00125]
      sphere_measurements: [0.05, 0.2]
      moving_obstacles_vels: [0.5, 2]
      moving_obstacles_directions: []
      moving_obstacles_trajectory_length: [0.05, 0.75]