# config that builds the env for the table ur5 experiment
run:
  load_model: False  
  model_path: ""  
  train:
    num_envs : 16  
    timesteps: 15000000 
    save_freq : 30000
    save_folder: "./models/weights"  
    save_name: "PPO_default"
    recurrent: False
    ppo_steps: 1024  
    batch_size: 512
    gamma: 0.99  
    tensorboard_folder: "./models/tensorboard_logs"
    custom_policy:
      use: False
      activation_function: "ReLU"  
      layers:
        - 128
        - 128
        - value_function:
          - 64
        - policy_function:
          - 32
          - 32
          - 16   
      lstm:
        lstm_hidden_size: 512
        n_lstm_layers: 2
        shared_lstm: False
        enable_critic_lstm: True

  eval:
    max_episodes: -1  
    logging: 1  
    display_delay: 0.00416666666 

env:
  max_steps_per_episode: 1024  
  use_physics_sim: True  # strictly speaking the original code had this at False
  physics_steps_per_env_step: 1
  sim_step: 0.00416666666  
  stat_buffer_size: 25  
  normalize_observations: False
  normalize_rewards: False
  robots:
    - type: "UR5" 
      config:
        name: "ur5_1"
        base_position: [0, 0, 1.1]
        base_orientation: [0, 0, 0]
        resting_angles: [-180, -45, -90, -135, 90, 0]
        control_mode: 0
        xyz_delta: 0.005
        rpy_delta: 0.005
      sensors:
        - type: "LidarSensorUR5"
          config:
            update_steps: 1
            add_to_observation_space: True
            add_to_logging: True
            indicator_buckets: 6
            ray_start: 0
            ray_end: 0.3
            ray_setup:
              ee_forward: [1, 1]
              wrist3_circle: [10, 10]
              wrist2_circle: [10, 10]
              wrist1_circle: [10, 10]
              upper_arm: [10, 10]
            render: False
            indicator: True
      goal:
        type: "PositionCollision"
        config:
          add_to_logging: True
          continue_after_success: True
          reward_success: 10
          reward_collision: -5
          reward_distance_mult: -0.01
          dist_threshold_start: 0.2
          dist_threshold_end : 0.01
          dist_threshold_increment_start: 0.01
          dist_threshold_increment_end: 0.001
          dist_threshold_overwrite: "None"

  world:
    type: "TableExperiment"
    config:
      workspace_boundaries: [-2, 2, -2, 2, 0, 5]
      num_obstacles: 5
      obstacle_velocities: []
      num_humans: 2
      human_positions: 
        - [0, 0, 0]
        - [1.6, 0, 1.4]
      human_rotations: 
        - [0, 0, 0]
        - [0, 0, 90]
      human_trajectories: 
        - [[-2, 2, 1.4], [2, 2, 1.5]]
        - []
      human_reactive: [False, True]
      ee_starts: []
      targets: []
      obstacle_positions: []
      obstacle_trajectories: []
      obstacle_training_schedule: False